is-live-account: true
binance-test:
  api-key: YOUR_API_TEST_KEY (OPTIONAL)
  secret-key: YOUR_SECRET_TEST_KEY (OPTIONAL)

binance-live:
  api-key: YOUR_API_KEY
  secret-key: YOUR_SECRET_KEY

telegram: YOUR_TELEGRAM_KEY (OPTIONAL)

config-path: config-local.yaml

strategy:
  - RSI
  - MA